version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
      PORT: 3333
    ports:
      - '3333:3333'
    command: npm run dev
  queue:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - '3001:3001'
    command: npm run queue
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alcoolmerce
    volumes:
      - alcoolmerce-db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
volumes:
  alcoolmerce-db:
